POST http://localhost:3333/events
Content-Type: application/json 


{
    "title": "Unite Summit",
    "details": "um Evento Para quem é apaixonado por programação",
    "maximumAttendees": 100
} 
###
POST http://localhost:3333/events/d8f1f375-760c-4911-b4a2-c985e518fd4e/attendees
Content-Type: application/json

{
    "name": "Diego Fernandes",
    "email": "diego2@rocket.com.br"
}